; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:uno]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 9600
build_flags = 
	-DLO_API_KEY=\"8d0264da509344169bb3fa89b071df72\"
	-DLO_DEVICE_ID=\"id_ul_dispozitivului_tau\"
	-DLO_SMS_ADMIN_NR=\"+40744946000\"
	-DLO_MQTT_HOST=\"liveobjects.orange-business.com\"
	-DLO_MQTT_PORT=1883
	-DLO_STREAM_ID=\"urn:lo:nsid:alphanumeric:1\"
	-DLO_TOPIC_PUB=\"dev/data\"
	-DLO_TOPIC_SUB=\"dev/cmd\"
lib_deps = miguelbalboa/MFRC522@^1.4.11
